name: mypy

on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Setup Python 3.10
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.10.2
        cache: pip
    - name: Install Dependencies
      run: |
        pip install mypy
    - name: mypy
      run: |
        mypy src/
